[package]
name = "micro-oc"
version = "0.1.0"
authors = ["Jolyon Saunders"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
cli-table = "0.4"
num-traits = "0.2"
nvapi-hi = "0.1.0"
